### ISSUE TITLE
type is not an allowed parameter on lua 5.4 centos 9 stream 

### ISSUE THREAD

**Issue by hoannv46** [PowerDNS/elasticsearch-lua#16]
Hi.

After install use luarocks make command for lastest commit, I write a simple lua script

```
local elasticsearch = require ("elasticsearch")

local client = elasticsearch.client{
  hosts = {
    {
      host = "127.0.0.1",
      port = "9200"
    }
  }
}


local res, status = client:index{
    index = "rgw",
    type = "Request",
    id = "id",
    body =
    {
        test1 = data,
        test2 = data2    
    }
}
print(res)
print(status)

```
this is ouput
```
nil
type is not an allowed parameter
```

All Enviroment Information 
OS : CentOS Stream release 9
Lua version : Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
Luarocks : LuaRocks 3.9.2, the Lua package manager                                                               

After remove line `type = "Request"` the script work.

My script was wrong or this is a bug ?

Thanks

**Comment by hoannv46** [comment]
@neilcook can you try my script. 
Thanks.

**Comment by neilcook** [comment]
The type parameter is no longer supported. It has been removed from Elasticsearch.

**Comment by hoannv46** [comment]
thanks. i will close this issue.
