### ISSUE TITLE
OpenSSL Devel package requirement for install

### ISSUE THREAD

**Issue by hoannv46** [PowerDNS/elasticsearch-lua#17]
Hi.

I am deploy elasticsearch-lua latest version on centos 9, it show error

Error: Failed installing dependency: https://luarocks.org/luasec-1.3.2-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
  No file openssl/ssl.h in /include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local

I must install openssl-devel package use command : yum install openssl-devel
 
My application run on docker. How i can install without openssl-devel package

Thanks.

**Comment by hoannv46** [comment]
@neilcook can you support me. Thanks.

**Comment by neilcook** [comment]
In your Dockerfile you can install openssl-devel:
 e.g.

RUN apt update -y && apt install openssl-devel
